teleport:
  # tpa,tpahere 等待时间
  waitTime: 3
  # tpa,tpahere 的使用间隔时间
  cdTime: 5
  # tpa,tpahere 超时时间
  timeout: 60

home:
  # home地址文件存放位置
  savePath: "./plugins/SimpleCommandSet/data/"

weather:
  # 隔多久运行一次天气锁定
  switchSecond: 1200
