name: SimpleCommandSet
main: org.yingye.scs.core.Core
version: 0.1.6
api-version: 1.17

commands:
  tpa:
    permission: scs.tpa.tpa

  tpahere:
    permission: scs.tpa.tpahere

  accept:
    permission: scs.tpa.accept

  deaccept:
    permission: scs.tpa.deaccept

  tpclear:
    permission: scs.tpa.tpclear

  back:
    permission: scs.back

  fly:
    permission: scs.fly.fly

  flyspeed:
    permission: scs.fly.flyspeed

  god:
    permission: scs.god

  home:
    permission: scs.home.home

  sethome:
    permission: scs.home.sethome

  delhome:
    permission: scs.home.delhome

  ohk:
    permission: scs.debug.ohk

  hb:
    permission: scs.debug.hb

  cl:
    permission: scs.debug.cl

  showdata:
    permission: scs.debug.showdata

  weatherinfo:
    permission: scs.world.weather.weatherinfo

  weatherlock:
    permission: scs.world.weather.weatherlock

  weatherunlock:
    permission: scs.world.weather.weatherunlock

  world:
    permission: scs.world.world

  remake:
    permission: scs.other.remake

permissions:
  # 权限集
  scs.tpa.*:
    children:
      tpa: true
      tpahere: true
      accept: true
      deaccept: true
      tpclear: true
  scs.home.*:
    children:
      home: true
      sethome: true
      delhome: true
  scs.debug.*:
    children:
      ohk: true
      hb: true
      cl: true
      showdata: true
  scs.world.*:
    children:
      world: true
      weather.*: true
  scs.world.weather.*:
    weatherinfo: true
    weatherlock: true
    weatherunlock: true
  scs.other.*:
    children:
      remake: true
  scs.fly.*:
    children:
      fly: true
      flyspeed: true

  # tpa
  scs.tpa.tpa:
    default: true
  scs.tpa.tpahere:
    default: true
  scs.tpa.accept:
    default: true
  scs.tpa.deaccept:
    default: true
  scs.tpa.tpclear:
    default: true

  # home
  scs.home.home:
    default: true
  scs.home.sethome:
    default: true
  scs.home.delhome:
    default: true

  # debug
  scs.debug.ohk:
    default: op
  scs.debug.hb:
    default: op
  scs.debug.cl:
    default: op
  scs.debug.showdata:
    default: true

  # back
  scs.back:
    default: true

  # fly
  scs.fly.fly:
    default: op
  scs.fly.flyspeed:
    default: op

  # god
  scs.god:
    default: op

  # world
  scs.world.world:
    default: op
  scs.world.weather.weatherlock:
    default: op
  scs.world.weather.weatherunlock:
    default: op
  scs.world.weather.weatherinfo:
    default: true

  # other
  scs.other.remake:
    default: true